---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  labels:
    accelerator.apps.tanzu.vmware.com/category: misc-samples
  name: hello-ytt
spec:
  git:
    url: https://github.com/sample-accelerators/hello-ytt
    ref:
      branch: main
      tag: tap-1.2
---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  labels:
    accelerator.apps.tanzu.vmware.com/category: misc-samples
  name: node-express
spec:
  git:
    url: https://github.com/sample-accelerators/node-express
    ref:
      branch: main
      tag: tap-1.2
