---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  labels:
    accelerator.apps.tanzu.vmware.com/category: platform
  name: tap-initialize
spec:
  git:
    url: https://github.com/sample-accelerators/tap-initialize
    ref:
      branch: main
      tag: tap-1.2
