apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: managed-accelerators
spec:
  serviceAccountName: accelerator-managed-resources

  fetch:
  - git:
      url: https://github.com/trisberg/application-accelerator-samples
      ref: origin/test
      subPath: managed-accelerators/resources

  template:
  - ytt: {}
  deploy: 
  - kapp: {}
